### ISSUE TITLE
Where is build.sh?

### ISSUE THREAD

**Issue by LiangYun36** [Iandiehard/diag-client-lib#13]

**Comment by Iandiehard** [comment]
There is no build.sh file , I have to update the readme file. 
Initially I thought of include build.sh file for locally building it.

You can also check https://github.com/Iandiehard/diag-client-lib/tree/main/.github which will give you an idea on how to build the library with dependencies

**Comment by Iandiehard** [comment]
ReadMe updated, Hence closing this issue
